# Generated by Django 5.1.6 on 2025-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_name_stocks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='image',
            field=models.ImageField(default=1, upload_to='stocks/'),
            preserve_default=False,
        ),
    ]
