# Generated by Django 5.1.6 on 2025-03-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stocks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='image',
        ),
    ]
